ticket.sys bearbeiten
Datei öffnen
Aktuelle Datei neu laden
Speichern
Speichern unter
Beenden
Datei
Neues Ticket
Neues Ticket.sys
Ticket.sys importieren
Bearbeiten
Schlüssel beim Importieren überschreiben
Genauere Farbzuordnung benutzen
Optionen
Über
Hilfe
Ticket-Optionen
Allgemein
App-Infos
Diverses
Ticket-Daten
Titel:
ISBN:
Unbekannter Wert #1:
Unbekannter Wert #2:
Ticket exportieren
Ticket Daten ersetzten
Ticket löschen
ticket.sys auswählen
iQue Player Systemdateien
Alle Dateien
Diese Date ist kein gültiges ticket.sys!\nTicket #1 magic: {}
Keine gefunden
Magic:
Größe des Vorschaubildes:
Größe des Titelbildes:
Vorschaubild:
Titelbild:
SK abrufen erlauben:
CID:
Ticket ID:
None
Datei zum Speichern auswählen
Ungültiger Wert für {} {}\nStelle sicher, dass sie ein {}-byte langer Hexadezimalwert ist!
Titel- oder Vorschaulänge is falsch. Informiere Jynji hierüber oder wähle ein weniger komplexes Bild
numTickets ist falsch! Informiere Jynji darüber was du getan hast, bevor du die Ticket Datei gespeichert hast.
Wähle PNG format aus {} Bild
Titel
Vorschaubild
PNG-Datei
Wähle zuerst ein Ticket aus!
Bist du sicher das du das Ticket für {} löschen willst? Dies kann nicht rückgängig gemacht werden!
ticket.sys auswählen
iQue Player Ticket-Dateien
Diese Datei ist kein gültiges\n Ticket Magic: {}
Diese Dateigröße ist falsch! Zum importieren einer CMD- oder contentDesc- Datei, bitte ein neues Ticket erstellen und die Datei ersetzen-Funktion verwenden.
iQue Player Inhaltsbeschreibung
iQue player Inhaltsmetadaten
Wähle Datei zum importiern
Binärdateien
Die ausgewählte Datei ist scheinbar keine contentDesc oder Inhaltsmetadateien-Datei! Mit dem Importieren von {} bytes fortfahren?
Die ausgewählte Datei sieht wie eine komplette Ticket-Datei aus! Als Ticket importieren? ('Nein' wird den Import abbrechen)
Ist ein Test-Ticket
ID:
Version {} des ticket.sys Editor von Jynji. Achte auf diesen Bereich!\nAktuelle numTickets: {}\n\nChinesische Übersetzung: tenyuhuang, SKSA\nFranzösische Übersetzung: MelonSpeedruns\nDeutsche Übersetzung: Mr_ZG, BY\nItalienische Übersetzung: asper\nKroatische Übersetzung: LuLGuy9999
Tickets sortieren
English
中文
Sprache
Français
Deutsch
Italiano
Hrvatski
繁體中文