ticket.sys bearbeiten
Datei öffnen
Aktuelle Datei neu laden
Speichern
Speichern unter
Beenden
Datei
Neues Ticket
Neues Ticket.sys
Ticket.sys importieren
Bearbeiten
Schlüssel beim Importieren überschreiben
Genauere Farbzuordnung benutzen
Optionen
Über
Hilfe
Ticket-Optionen
Allgemein
App-Infos
Diverses
Ticket-Daten
Titel:
ISBN:
Unbekannter Wert #1:
Unbekannter Wert #2:
Ticket exportieren
Ticket Daten ersetzten
Ticket löschen
ticket.sys auswählen
iQue Player Systemdateien
Alle Dateien
Diese Date ist kein gültiges ticket.sys!\nTicket #1 magic: {}
Keine gefunden
Magic:
Größe des Vorschaubildes:
Größe des Titelbildes:
Vorschaubild:
Titelbild:
Erlaubte SK Abrufe:
CID:
Ticket ID:
Warnung: Titelbilder müssen einfarbig sein, einige Daten werden bei dem Versuch verloren gehen, das ausgewählte Bild in einen Titel zu konvertieren
Datei zum Speichern auswählen
Ungültiger Wert für {} {}\nStelle sicher, dass sie ein {}-byte langer Hexadezimalwert ist!
Titel- oder Vorschaulänge is falsch. Informiere Jynji hierüber oder wähle ein weniger komplexes Bild
numTickets ist falsch! Informiere Jynji darüber was du getan hast, bevor du die Ticket Datei gespeichert hast.
Wähle PNG format aus {} Bild
Titel
Vorschaubild
PNG-Datei
Wähle zuerst ein Ticket aus!
Bist du sicher das du das Ticket für "{}" löschen willst? Dies kann nicht rückgängig gemacht werden!
ticket.sys auswählen
iQue Player Ticket-Dateien
Diese Datei ist kein gültiges\n Ticket Magic: {}
Diese Dateigröße ist falsch! Zum importieren einer CMD oder contentDesc- Datei, bitte ein neues Ticket erstellen und die 'Datei ersetzen'-Funktion verwenden.
iQue Player Inhaltsbeschreibungsdaten
iQue player Inhaltsmetadaten
Wähle Datei zum importieren
Binärdateien
Die ausgewählte Datei ist scheinbar keine contentDesc oder Inhaltsmetadateien-Datei! Mit dem Importieren von {} bytes fortfahren?
Die ausgewählte Datei sieht wie eine komplette Ticket-Datei aus! Als Ticket importieren? ('Nein' wird den Import abbrechen)
Ist ein Test-Ticket:
ID:
Version {} des ticket.sys Editor von Jynji. Achte auf diesen Bereich!\. Aktuelle numTickets: {}\n\n Chinesische Übersetzung: tenyuhuang, SKSA\nFranzösische Übersetzung: MelonSpeedruns\nDeutsche Übersetzung: Mr_ZG, BY\nItalienische Übersetzung: asper\nKroatische Übersetzung: LuLGuy9999
Tickets sortieren
English
中文
Sprache
Français
Deutsch
Italiano
Hrvatski





Position EEPROM RDRAM:
Größe EEPROM:
Position Flash RDRAM:
Größe Flash:
Position SRAM RDRAM
Größe SRAM:
Position des Controller Pak 0 RDRAM:
Position des Controller Pak 1 RDRAM:
Position des Controller Pak 2 RDRAM:
Position des Controller Pak 3 RDRAM:
Größe der Controller Pak:
osRomBase:
osTvType:
osMemSize:
Unbekannter Wert #3:
Unbekannter Wert #4:
Magic:
Anzahl der .u0x Dateien:
None
None
Vorschaubild
Titelbild:
None
Padding:
CRL Autorität Zertifikat:
CRL Sicherheits Version:
Größe:
Unbekannter Wert #5:
Titlekey IV:
SHA-1 hash:
Content IV:
Exec flags:
Hardware Zugriffsrechte:
None
CMD BBID:
BBID Zertifikat:
CID:
Titlekey:
Signatur:
Ticket BBID:
Ticket ID:
Typ von Demo:
Minuten oder Starts für Demo:
Padding:
Ticket CRL version:
Titlekey IV 2:
ECC Offizieller Schlüssel:
Ticket Zertifikat:
Signatur: