ticket.sys editor
Open file
Reload current file
Save
Save as
Exit
File
New ticket
New ticket.sys
Import ticket.dat
Edit
Overwrite keys when importing
Use more accurate colour mapping
Options
About
Help
Ticket options
General
App info
Misc.
Ticket data
Title:
ISBN:
Unknown value #1:
Unknown value #2:
Export ticket
Replace ticket data
Delete ticket
Select ticket.sys
iQue Player system files
All files
This file is not a valid ticket.sys!\nTicket #1 magic: {}
None found
Magic:
Thumb image length:
Title image length:
Thumb image:
Title image:
Allowed SK calls:
CID:
Ticket ID:
None
Select file to save to
Invalid value for {} {}\nPlease make sure it is {}-byte long hex integer!
Title or thumb image length is incorrect! Please tell Jynji that this message appeared, or try a less complex image.
numTickets is incorrect! Please report this to Jynji, along with what you were doing before saving the ticket file.
Select PNG format {} image
title
thumb
Portable Network Graphics file
Please select a ticket first!
Are you sure you want to delete the ticket for "{}"? This can't be undone!
Select ticket.dat
iQue Player ticket files
This file is not a valid ticket!\nTicket magic: {}
This file's length is incorrect! To import a CMD or contentDesc file, please make a new ticket and use the 'Replace data' function.
iQue Player content description files
iQue Player content metadata files
Select data to import
Binary files
The file you selected does not appear to be a contentDesc file or content metadata file! Continue to import {} bytes?
The file you selected appears to be a complete ticket file! Import as ticket? (Selecting 'No' will cancel the import.)
Is trial ticket:
ID:
Version {} of ticket.sys editor by Jynji. Watch this space!\nCurrent numTickets: {}\n\nChinese translation: tenyuhuang, SKSA\nFrench translation: MelonSpeedruns\nGerman translation: Mr_ZG, BY\nItalian translation: asper\nCroatian translation: LuLGuy9999
Sort tickets
English
简体中文
Language
Français
Deutsch
Italiano
Hrvatski
繁體中文