ticket.sys editor
Open file
Reload current file
Save
Save as
Exit
File
New ticket
New ticket.sys
Import ticket.dat
Edit
Overwrite keys when importing
Use more accurate colour mapping
Options
About
Help
Ticket options
General
App info
Misc.
Ticket data
Title:
ISBN:
Unknown value #1:
Unknown value #2:
Export ticket
Replace ticket data
Delete ticket
Select ticket.sys
iQue Player system files
All files
This file is not a valid ticket.sys!\nTicket #1 magic: {}
None found
Magic:
Thumb image length:
Title image length:
Thumb image:
Title image:
Allowed SK calls:
CID:
Ticket ID:
Warning: Title images must be monochrome only, so some data will be lost trying to directly convert your selected image to a title.
Select file to save to
Invalid value for {} {}\nPlease make sure it is {}-byte long hex integer!
Title or thumb image length is incorrect! Please tell Jynji that this message appeared, or try a less complex image.
numTickets is incorrect! Please report this to Jynji, along with what you were doing before saving the ticket file.
Select PNG format {} image
title
thumb
Portable Network Graphics file
Please select a ticket first!
Are you sure you want to delete the ticket for "{}"? This can't be undone!
Select ticket.dat
iQue Player ticket files
This file is not a valid ticket!\nTicket magic: {}
This file's length is incorrect! To import a CMD or contentDesc file, please make a new ticket and use the 'Replace data' function.
iQue Player content description files
iQue Player content metadata files
Select data to import
Binary files
The file you selected does not appear to be a contentDesc file or content metadata file! Continue to import {} bytes?
The file you selected appears to be a complete ticket file! Import as ticket? (Selecting 'No' will cancel the import.)
Is trial ticket:
ID:
Version {} of ticket.sys editor by Jynji. Watch this space!\nCurrent numTickets: {}\n\nChinese translation: tenyuhuang, SKSA\nFrench translation: MelonSpeedruns\nGerman translation: Mr_ZG, BY\nItalian translation: asper\nCroatian translation: LuLGuy9999
Sort tickets
English
中文
Language
Français
Deutsch
Italiano
Hrvatski





EEPROM RDRAM location:
EEPROM size:
Flash RDRAM location:
Flash size:
SRAM RDRAM location:
SRAM size:
Controller Pak 0 RDRAM location:
Controller Pak 1 RDRAM location:
Controller Pak 2 RDRAM location:
Controller Pak 3 RDRAM location:
Controller Pak size:
osRomBase:
osTvType:
osMemSize:
Unknown value #3:
Unknown value #4:
Magic:
Number of .u0x files:
None
None
Thumb image:
Title image:
None
Padding:
Certificate Authority CRL version:
Content Protection CRL version:
Size:
Unknown value #5:
Titlekey IV:
SHA-1 hash of plaintext:
Content IV:
Exec flags:
Hardware access rights:
None
CMD BBID:
CMD certificate:
CID:
Titlekey:
Signature:
Ticket BBID:
Ticket ID:
Type of trial:
Minutes or launches for trial:
Padding:
Ticket CRL version:
Titlekey IV 2:
ECC public key:
Ticket certificate:
Signature: