Éditeur ticket.sys
Ouvrir un fichier
Recharger le fichier
Sauvegarder
Sauvegarder sous
Quitter
Fichier
Nouveau Ticket
Nouveau ticket.sys
Importer un ticket.dat
Modifier
Remplacer les clés lors de l'importation
Utilisez des couleurs plus précises
Paramètres
À propos
Aide
Options de Ticket
Général
Infos de l'app
Divers.
Données du Ticket
Titre:
ISBN:
Valeur Inconnue #1:
Valeur Inconnue #2:
Exporter le Ticket
Remplacer les données
Supprimer le Ticket
Sélectionner un Ticket.sys
Fichiers système du iQue Player
Tout les fichiers
Ce fichier n'est pas un ticket.sys valide !\nTicket #1 magie: {}
Aucun trouvé
Magie:
Longueur de l'image bannière:
Longueur de l'image titre:
Image bannière:
Image titre:
Appels SK autorisés:
CID:
ID du Ticket:
None
Sélectionnez un fichier à remplacer.
Valeur non valide pour {} {}\nVeuillez vous assurer qu'il s'agit d'une valeur longue de {} bytes.
La longueur du titre ou de l'image de bannière est incorrecte! Merci de dire à Jynji que ce message est apparu ou d'essayer une image moins complexe.
numTickets est incorrect! Signalez-le à Jynji, ainsi que ce que vous faisiez avant de sauvegarder le fichier de ticket.
Sélectionez une image PNG {}
titre
bannière
Fichier Portable Network Graphics
Veuillez d'abord sélectionner un ticket!
Êtes-vous sûr de vouloir supprimer le ticket pour {} ? Cela ne peut pas être annulé!
Sélectionnez le ticket.dat
Fichiers Ticket iQue Player
Ce fichier n’est pas un ticket valide !\nTicket magie: {}
La longueur de ce fichier est incorrecte! Pour importer un fichier CMD ou contentDesc, créez un nouveau ticket et utilisez la fonction Remplacer les données.
Fichiers de description du contenu du iQue Player
Fichiers de métadonnées du contenu du iQue Player
Sélectionnez les données à importer
Fichiers binaires
Le fichier que vous avez sélectionné ne semble pas être un fichier contentDesc ni un fichier de métadonnées ! Continuer à importer {} octets ?
Le fichier que vous avez sélectionné semble être un fichier de ticket complet! Importer en tant que ticket? (Si vous sélectionnez 'Non', l'importation sera annulée.)
Est un Ticket d'essai:
ID:
Version {} de l'éditeur de ticket.sys par Jynji. Surveillez cet endroit !\nNuméros actuels: {} \n\nTraduction en Français: tenyuhuang, SKSA\nTraduction en Français: MelonSpeedruns\nTraduction en Allemand: Mr_ZG, BY\nTraduction en Italien: asper\nTraduction en Croate: LuLGuy9999
Trier les tickets
English
简体中文
Langue
Français
Deutsch
Italiano
Hrvatski
繁體中文