ticket.sys Urednik
Otvori Datoteku
Ponovno učitaj Datoteku
Spremi
Spremi na...
Izađi
Datoteka
Novi Ticket
Novi Ticket.sys
Dodaj Ticket.sys
Uredi
Kljuć prepiši kod dodavanja
Koristi točniji Kontrast Boja
Opcije
Vise Informacija
Pomoć
Ticket Opcije
Generalno
O Aplikaciji
Misc
Ticket-informacije
Titel:
ISBN:
Nepoznata Jedinica #1
Nepoznata Jedinica #2
Exportiraj Ticket
Zamjeni Ticket
Izbriši Ticket
Otvori ticket.sys
iQue Player System Datoteke
Sve Datoteke
Ova Datoteka Nema vrijedni ticket.sys!\nTicket #1 magija: {}
Nije Pronađeno
Magija:
Velicina Predgledne Slike:
Velicina Titla:
Pregled:
Titelslika:
Dopusti Dozivanje SK:
CID:
Ticket ID:
None
Izaberi Datoteku za Spremanje
Nevaljana Vrijednos za {} {}\nJeste li sigurni da {}-byte jedna duga Hex vrijednost
Titel ili predgled dužina je kriva Informiraj Jynji Oko ove stavke ii uzmi manje kompliciranu Sliku
numTicket je krivi! Informiraj Jynji oko šta ste napravili i što ste napravili prije nego ste spremili Ticket Datoteku
Izaberi PNG format iz {} Slika
Titel
Palac 
PNG-Datoteka
Izaberi Prvo Tiket
Je si li siguran da hoćes izbrisati {} ovo se ne može vise Upotrijebiti!
izaberi ticket.sys
iQue Player Ticket Datoteka
Ova Datoteka ima jednu nevaljanu Velićinu\nTicketa Magija: {}
Ova Velicina je Kriva! za importiranje jedne CMD ili contentDesc- Datotke i napravi novi Ticket 
iQue Player opisanje
iQue Player meta Datoteke
Dodaj datoteku za imporitranje
Binarske Datoteke
Izabrana Datoteka nije contentDesc ili opisanjska-Datoteka sa importiranjem od {} byta nastaviti ?
Izabrana Datoteka izgleda kao Dovršena Ticket-Datoteka svejedno inportirarj? ('Ne' Prekini Import)
Jeli Jedan Test Ticket
ID:
Verzija {} Ticket.sys Urednika od Jynji. Pazi na ovaj teretorij!\nAktualni Broj Ticketa: {}\n\nKineski Prijevod: tenyuhuang, SKSA\nFrancuski Prijevod: MelonSpeedruns\nNjemački Prijevod: Mr_ZG, BY\nItalianski Prijevod: asper\nHrvatski Prijevod: LuLGuy9999
Sortiraj Tikete
English
简体中文
Jezik
Français
Deutsch
Italiano
Hrvatski
繁體中文