Editor del ticket.sys
Apri file
Ricarica file corrente
Salva
Salva con nome
Esci
File
Nuovo ticket
Nuovo ticket.sys
Importa ticket.dat
Modifica
Sovrascrivi le chiavi mentre si importa
Utilizza color mapping accurato
Opzioni
Informazioni
Aiuto
Opzioni ticket
Generale
Info app
Varie
Dati ticket
Titolo
ISBN:
Valore sconosciuto #1
Valore sconosciuto #2
Esporta ticket
Sostituisci dati ticket
Cancella ticket
Seleziona ticket.sys
Files di sistema iQue Player
Tutti i files
Questo non è un ticket.sys valido!nTicket #1 magic: {}
Non trovato
Magic:
Lunghezza immagine di anteprima:
Lunghezza titolo immagine:
Immagine di anteprima:
Immagine titolo:
Calls SK permesse:
CID:
Ticket ID:
Attenzione: Le immagini devono essere soltanto monocromatiche, quindi alcuni dati andranno persi cercando di convertire direttamente l'immagine selezionata in un titolo. 
Seleziona file in cui salvare
Valore non valido {} {}\nAssicurarsi che sia un valore hex intero lungo {}-byte
Lunghezza immagine titolo o di anteprima non corretta! Informa Jynji della comparsa di questo messaggio oppure prova con una immagine meno complessa.
numTickets non corretto! Informa Jynji di questo errore, assieme ad informazioni riguardo cosa stavi facendo prima di salvare il file ticket.
Seleziona immagine {} in formato PNG
titolo
anteprima
Portable Network Graphics file
Si prega di selezionare prima un ticket
Sicuro di voler cancellare il ticket per "{}"? Questa operazione non puo'essere annullata!
Seleziona ticket.dat
Ticket files iQue Player
Questo non è un file ticket valido!\nTicket magic: {}
La lunghezza del file non è corretta! Per importare un CMD o un file contentDesc, creare un nuovo ticket ed utilizzare la funzione "Sostituisci dati".
Files descrizione contenuto iQue Player
Files metadata contenuto iQue Player
Seleziona dati da importare
Files binari
Il file selezionato non sembra essere un file contentDesc o metadata content! Continuare ad importare {} bytes?
Il file selezionato sembra essere un file ticket completo! Importarlo come ticket? (Selezionando 'No' l'operazione di importazione verrà annullata.)
E'un ticket dimostrativo:
ID:
ticket.sys editor versione {} by Jynji. Controlla questo spazio!\nCurrent numTickets: {}\n\nTraduzione Cinese: tenyuhuang, SKSA\nTraduzione Francese: MelonSpeedruns\nTraduzione Tedesca: Mr_ZG, BY\nTraduzione Italiana: asper\nTraduzione Croata: LuLGuy9999
Ordina tickets
English
中文
Lingua
Français
Deutsch
Italiano
Hrvatski





Locazione EEPROM RDRAM:
Dimensione EEPROM:
Locazione flash RDRAM:
Dimensione flash:
Locazione SRAM RDRAM:
Dimensione SRAM:
Locazione Controller Pak 0 RDRAM:
Locazione Controller Pak 1 RDRAM:
Locazione Controller Pak 2 RDRAM:
Locazione Controller Pak 3 RDRAM:
Dimensione controller Pak:
osRomBase:
osTvType:
osMemSize:
Valore sconosciuto #3:
Valore sconosciuto #4:
Magic:
Numero dei files .u0x:
None
None
Immagine anteprima
Immagine titolo
None
Riempimento (padding):
Versione Certificate Authority CRL:
Versione Content Protection CRL:
Dimensione:
Valore sconosciuto #5:
Titlekey IV:
Hash SHA-1 del testo non criptato:
Content IV:
Flags Exec:
Permessi hardware:
None
CMD BBID:
Certificato BBID:
CID:
Titlekey:
Firma:
Ticket BBID:
Ticket ID:
Tipo di versione dimostrativa:
Minuti o numero avvii per la versione dimostrativa:
Riempimendo (padding):
Versione ticket CRL:
Titlekey IV 2:
Chiave pubblica ECC:
Certificato ticket:
Firma: