神游机程序数据库编辑器
打开
重新加载当前文件
保存
另存为
退出
文件
新建信息表
新建程序数据库
导入ticket.dat
编辑
导入时覆盖密钥
导入图片时使用更精准的颜色映射
设置
关于
帮助
信息表设置
常规
程序信息
其他
信息表数据
标题：
ISBN：
未知数值 #1
未知数值 #2
导出信息表
替换信息表数据
删除信息表
选择ticket.sys
神游机系统文件
所有文件
这不是有效的ticket.sys！\n信息表#1的幻数：{}
未填写
幻数：
缩略图文件大小：
标题图片文件大小：
缩略图：
标题图片：
And this one
程序编号：
信息表ID：
警告：请选择一张黑白图片作为标题图。如果选择的图片为彩色，在转换过程中可能会有损失。
选择要保存的文件名
{}的值“{}”无效！\n请输入长度为{}字节的16进制整数。
图片文件大小有误！请将此问题反馈给Jynji，或者更换一张简单一些的图片。
numTickets有误！请将此问题反馈给Jynji，描述一下错误产生之前您所做的操作。
请选择一张PNG格式的{}
标题图片
缩略图
PNG图片文件
请先选择一张信息表！
你确定要删除“{}”的信息表吗？本操作无法撤销！
选择ticket.dat
神游机程序信息表文件
这不是一个有效的信息表！\n信息表幻数：{}
文件大小有误！想要导入文件，请新建一个数据表并选择“替换数据”。
神游机内容描述文件
神游机内容元数据文件
请选择要导入的数据
二进制数据文件
所选文件不像是描述文件或者元数据文件，依然要导入{}字节的数据吗？
所选文件好像是一个完整的信息表，要作为信息表导入吗？\n（选择“否”将取消导入）
是否为试玩版：
ID：
神游机程序数据库编辑器 by Jynji\n版本：{}\n静候佳音！\n当前数据库中有{}张信息表。\n\n中文版翻译：tenyuhuang、SKSA\n法语版翻译：MelonSpeedruns\n德语版翻译：Mr_ZG、BY\n意大利语翻译：asper\n克罗地亚语版翻译：LuLGuy9999
重排信息表顺序
English
中文
语言
Français
Deutsch
Italiano
Hrvatski





EEPROM RDRAM位置：
EEPROM大小：
Flash RDRAM位置：
Flash大小：
SRAM RDRAM位置：
SRAM大小：
Controller Pak 0 RDRAM位置：
Controller Pak 1 RDRAM位置：
Controller Pak 2 RDRAM位置：
Controller Pak 3 RDRAM位置：
Controller Pak大小：
osRomBase：
osTvType：
osMemSize：
未知数值 #3：
未知数值 #4：
幻数：
.u0x文件的个数：
None
None
缩略图：
标题图片：
None
填充：
证书颁发机构CRL版本：
内容保护CRL版本：
应用程序大小：
未知数值 #5：
Titlekey IV：
明文数据的SHA-1：
内容IV：
执行参数：
硬件访问权限：
None
内容元数据BBID：
内容元数据证书：
程序编号：
Titlekey：
签名：
信息表BBID：
信息表ID：
试玩类型：
试玩版总共可用的分钟数/次数：
填充：
信息表CRL版本：
Titlekey IV 2：
ECC公钥：
信息表证书：
签名：